---
id: 6733bee844600f35c05b8264
title: Como funciona o try...catch...finally?
challengeType: 19
dashedName: how-does-try-catch-finally-work
---

# --description--

Na lição anterior, você aprendeu como lançar exceções em seus programas. Nesta lição, vamos ver como tratar esses erros de forma elegante em um bloco `try…catch…finally`.

O bloco `try` é usado para envolver código que pode gerar um erro. Ele atua como um espaço seguro para tentar algo que pode falhar.

O bloco `catch` captura e trata erros que ocorrem no bloco `try`. Você pode usar o objeto `Error` dentro do `catch` para inspecionar o que deu errado.

O bloco `finally` é executado após os blocos `try` e `catch`, independentemente de um erro ter ocorrido. É comumente usado para tarefas de limpeza, como fechar arquivos ou liberar recursos.

Aqui está um exemplo de uso de um bloco `try…catch`:

```js
function processInput(input) {
  if (typeof input !== "string") {
    throw new TypeError("Input must be a string.");
  }

  return input.toUpperCase();
}

try {
  console.log("Starting to process input...");
  const result = processInput(9);
  console.log("Processed result:", result);
} catch (error) {
  console.error("Error occurred:", error.message);
} 
```

Neste exemplo, temos uma função chamada `processInput` que primeiro verifica se o `input` não é do tipo `string`. Se for esse o caso, então lançamos um erro. Caso contrário, retornamos o resultado de usar o método `toUpperCase` no `input`.

Chamamos a função dentro de um bloco `try`. Como a chamada da função gera um erro, ele será capturado dentro do bloco `catch` e a mensagem de erro será exibida no console. 

O erro passado para o bloco `catch` é um objeto `Error` que contém informações sobre esse erro. Neste caso, estamos usando a propriedade `message` que exibe informações legíveis para humanos ao usuário. 

Estamos usando o `console.error` porque ele foi projetado especificamente para registrar erros. Em muitos navegadores modernos, a saída de `console.error()` aparece em vermelho no console.

A declaração `finally` é executada independentemente de uma exceção ter sido lançada ou não.

```js
try {
  // Code that might throw an error
} catch (error) {
  // Code to handle the error
} finally {
  // Code that runs regardless of whether an error occurred or not
}
```

Um bom caso de uso para a declaração `finally` é se você estiver trabalhando com arquivos. Em JavaScript, você pode abrir um arquivo e usar um bloco `try` para escrever dados no arquivo. Se houver algum erro, você pode usar o `catch` para capturar esses erros. Então use a declaração `finally` para fechar o arquivo.

# --questions--

## --text--

O que melhor descreve o bloco `try`?

## --answers--

É para executar o código novamente automaticamente após ocorrer um erro.

### --feedback--

Pense na ordem dos blocos em declarações `try…catch…finally` e nos tipos de tarefas que cada bloco executa.

---

É para lidar com erros.

### --feedback--

Pense na ordem dos blocos em declarações `try…catch…finally` e nos tipos de tarefas que cada bloco executa.

---

É para configuração antes de um erro ser lançado.

### --feedback--

Pense na ordem dos blocos em declarações `try…catch…finally` e nos tipos de tarefas que cada bloco executa.

---

É um invólucro seguro para código que pode gerar um erro.

## --video-solution--

4

## --text--

Qual bloco sempre é executado mesmo se ocorrer um erro?

## --answers--

`try`

### --feedback--

Este bloco é frequentemente usado para tarefas de limpeza.

---

`catch`

### --feedback--

Este bloco é frequentemente usado para tarefas de limpeza.

---

`finally`

---

`throw`

### --feedback--

Este bloco é frequentemente usado para tarefas de limpeza.

## --video-solution--

3

## --text--

Qual é o propósito do bloco `catch`?

## --answers--

Para executar código que pode gerar um erro.

### --feedback--

Este bloco é ativado quando algo dá errado no bloco `try`.

---

Para definir um espaço seguro para a execução de código.

### --feedback--

Este bloco é ativado quando algo dá errado no bloco `try`.

---

Para lidar com erros de forma elegante sem travar o programa.

---

Para sempre executar, independentemente de erros.

### --feedback--

Este bloco é ativado quando algo dá errado no bloco `try`.

## --video-solution--

3
